# Clash Verge 配置文件示例
port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info

proxies:
  - name: "Proxy1"
    type: ss
    server: server1.example.com
    port: 443
    cipher: aes-256-gcm
    password: "password1"

proxy-groups:
  - name: "Auto"
    type: url-test
    proxies:
      - "Proxy1"
    url: "http://www.gstatic.com/generate_204"
    interval: 300

rules:
  - DOMAIN-SUFFIX,google.com,Auto
  - DOMAIN-SUFFIX,example.com,Auto
  - GEOIP,CN,DIRECT
  - MATCH,Auto
